export const SCREENS = {
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  COURSES: "/courses",
  CREATE_COURSE: "/create-course",
  GET_COURSE: (id?: string) => `/course/${id ? id : ":id"}`,
  EDIT_COURSE: (id?: string) => `/edit-course/${id ? id : ":id"}`,
  PROFILE: "/profile",
  PLANS: "/plans",
  GET_PLAN: (id?: string) => `/plans/${id ? id : ":id"}`,
  EDIT_PLAN: (id?: string) => `/edit-plan/${id ? id : ":id"}`,
  CREATE_PLAN: "/create-plan",
  USERS_TABLE: "/users",
  ORDERS: "/orders",
  INVOICES: "/invoices",
};
