export const SCREENS = {
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  COURSES: "/courses",
  CREATE_COURSE: "/create-course",
  GET_COURSE: (id: string) => `/course/${id}`,
  PROFILE: "/profile",
  PLANS: "/plans",
  GET_PLAN: (id: string) => `/plans/${id}`,
  CREATE_PLAN: "/create-plan",
  USERS_TABLE: "/users",
  ORDERS: "/orders",
  INVOICES: "/invoices",
};
